### ISSUE TITLE
connection to home-assistant fails.

### ISSUE THREAD

**Issue by jjlacrampe** [giaever-online-iot/code-server#1]
Hello,
When I try to onncet, I get the message :
$ sudo snap connect code-server:vscs-content home-assistant-snap:configurations
erreur : cannot perform the following tasks:
- Connecter code-server:vscs-content à home-assistant-snap:configurations (connection not allowed by slot rule of interface "content")

**Comment by jmgiaever** [comment]
Hi,

Connect to the slot `home-assistant-snap:vscs-content` instead.

**Comment by jjlacrampe** [comment]
Thanx for your help : anything works fine!
