### ISSUE TITLE
configurator stays in the dashboard of homme assistant while it has been removed

### ISSUE THREAD

**Issue by jjlacrampe** [giaever-online-iot/code-server#2]
As far as, using https, I had no more access to configurator, I installed code-server and removed connection between home-assistant and home-assistant-configurator and then removed home-assistant-configurator  itself.

Nevertheless configurator stays in the dashboard; how can I delete it?

Conversely is there any way to add code-server to the dashboard?

Thanx,

Best regards

**Comment by jmgiaever** [comment]
In the dashboard? Can you show me with a screenshot?

**Comment by jjlacrampe** [comment]
Of course, and thanx for your reaction
[image: image.png]

**Comment by jmgiaever** [comment]
Hi,

Sorry, nothing got attached.

**Comment by jjlacrampe** [comment]
it was included in the message, here it is joined

**Comment by jmgiaever** [comment]
Still nothing attached. I think you have to login to GitHub and attach it.

**Comment by jjlacrampe** [comment]
[configurator.pdf](https://github.com/giaever-online-iot/code-server/files/9947013/configurator.pdf)

**Comment by jjlacrampe** [comment]
![image](https://user-images.githubusercontent.com/46439070/200199713-3e611269-e5c6-4fba-9154-b4762e89ec38.png)

**Comment by jjlacrampe** [comment]
is it right now?

**Comment by jmgiaever** [comment]
Got it now, yes. You have to edit the iframe_panels or whatever the file is called in your configuration files. This is a HA specific setting.

**Comment by jjlacrampe** [comment]
Awesome, thanks!

I have installed the snap for code-server in https version; it seems to
start fine :
----------------------------------------------------------------------------------------
/snap/code-server/27/env/env-wrapper: line 7: warning: command
substitution: ignored null byte in input
/snap/code-server/27/env/env-wrapper: line 17: [: missing `]'
[2022-11-09T17:46:10.849Z] info  code-server 4.4.0
b088ec7adf9e17bc75215f79e21498eb40da03ed
[2022-11-09T17:46:10.850Z] info  Using user-data-dir
/var/snap/code-server/27/user-data
[2022-11-09T17:46:10.875Z] info  Using config file
/var/snap/code-server/27/config.yaml
[2022-11-09T17:46:10.875Z] info  HTTPS server listening on
https://192.168.1.2:8090/
[2022-11-09T17:46:10.875Z] info    - Authentication is enabled
[2022-11-09T17:46:10.875Z] info      - Using password from
/var/snap/code-server/27/config.yaml
[2022-11-09T17:46:10.875Z] info      - Using certificate for HTTPS:
/var/snap/code-server/common/fullchain.cer
[18:46:19] Extension host agent started.
-----------------------------------------------------------------------------------------------
but when I try to connect, I get this message :
-----------------------------------------------------------------------------------------------
[2022-11-09T17:46:22.485Z] error EACCES: *permission denied, mkdir
'/run/user/0'* Error: EACCES: permission denied, mkdir '/run/user/0'
-----------------------------------------------------------------------------------------------
I have :
- stopped the snap, (sudo snap stop code-server)
- manually created /run/user/0 as a sudoer (sudo mkdir /run/user/0)
- started the snap (sudo snap start code-server)

And then I could connect from anywhere.

BUT : *when I reboot, the directorty /run/user/0 disappears and I have do
make it once more.*

Any suggestion?
