### ISSUE TITLE
snap code-server cannot start

### ISSUE THREAD

**Issue by jjlacrampe** [giaever-online-iot/code-server#3]
Hello
in order to use this snap with ubuntu 22.04 LTS, I have to create manually as a sudoer the directory /run/user/0 and I have to do it every time I reboot!
Otherwise I get the message :
![image](https://user-images.githubusercontent.com/46439070/202423369-86944683-b006-4fe1-96b2-fe41b2f8d4a2.png)
How to prevent this?

**Comment by jmgiaever** [comment]
Hi,

This is a issue with the snap installation, not a problem with the snap package. Sounds like a permission issue in you setup, but I can't help you here. 

You have to seek advice in the snapcraft or askubuntu forums.
