### ISSUE TITLE
get code-server to show in HA

### ISSUE THREAD

**Issue by KwisatzJim** [giaever-online-iot/code-server#4]
Hi, 

forgive my ignorance with this question, I'm getting started with snap and HA and code-server. I've got HA up and running, got the code-server up and running and can access it on port 8080. How do I get code-server to show up inside HA? It's a new install of each and the only changes to any configs I've made is to code-server to change the IP address.

thanks

**Comment by jmgiaever** [comment]
https://www.home-assistant.io/integrations/panel_iframe/
